### Get server information
GET http://localhost:3001/info

### Update existing person
PUT http://localhost:3001/api/persons/65fd69189f4ece00bc418038
Content-Type: application/json

{ 
      "name": "ADOLF", 
      "number": "323122"
}

### Get all persons
GET http://localhost:3001/api/persons

### Get a person that exists
GET http://localhost:3001/api/persons/65fd69189f4ece00bc418038

### Get a person that does not exist
GET http://localhost:3001/api/persons/100

### Correctly Adding a Person
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "name": "Pettter", 
      "number": "39-eeeeeeeeeeeeee23-6423122"
}

### Wrongly Adding a Person (Missing name)
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "name": "", 
      "number": "39-23-6423122"
}

### Wrongly adding a Person (Name already exists)
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "name": "Peter", 
      "number": "39-23-6423122"
}
### Deleting a person that exists
DELETE http://localhost:3001/api/persons/1

### Deleting a person that does not exist
DELETE http://localhost:3001/api/persons/1000000

### Requesting a nonexistant route
GET http://localhost:3001/peterparkers

