### Add a person
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "name": "yooo", 
      "number": "10-22-334455"
}

### Get people
GET http://localhost:3001/api/persons